services:
  - type: web
    name: stryktipset-backend
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome@131.0.6778.85
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-131.0.6778.85/chrome-linux64/chrome
